"""workflow_support

Revision ID: 7313b592b2e1
Revises: 43038a692f46
Create Date: 2026-08-12 19:19:15.731279
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7313b592b2e1'
down_revision: Union[str, Sequence[str], None] = '43038a692f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('change_requests', sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False))
    op.create_index('ix_orders_status_approved_at', 'orders', ['status', 'approved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_status_approved_at', table_name='orders')
    op.drop_column('change_requests', 'requested_at')
    # ### end Alembic commands ###
